name: mycreditloans
description: Take your investments to the next level.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.1 
  cupertino_icons: ^1.0.2
  image_picker: ^0.8.4+2  
dev_dependencies:
  flutter_native_splash: ^1.2.3
  flutter_launcher_icons: "^0.9.2"
  flutter_test:
    sdk: flutter

#native splash
flutter_native_splash:
  color: "#2C64E3"
  image : assets/logo.png
flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  adaptive_icon_background: "#2C64E3"
  adaptive_icon_foreground: "assets/transparent_logo.png"
flutter:
  uses-material-design: true
  assets:
      - assets/
      - assets/fonts/
  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-SemiBold.otf
          weight: 700
        - asset: assets/fonts/Gilroy-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Gilroy-Medium.otf
          weight: 500
        - asset: assets/fonts/Gilroy-Regular.otf
          weight: 400
